kind = "DojoModel"
class_hash = "0x11508f0327c6fff90b9242475aa33eca07e653f8c8ce7fc0ea3f516408e7bf7"
original_class_hash = "0x11508f0327c6fff90b9242475aa33eca07e653f8c8ce7fc0ea3f516408e7bf7"
abi = "manifests/dev/abis/base/models/dojo_starter_models_skill_skill.json"
name = "dojo_starter::models::skill::skill"

[[members]]
name = "entityId"
type = "ContractAddress"
key = true

[[members]]
name = "gameId"
type = "u32"
key = true

[[members]]
name = "attack"
type = "u16"
key = false

[[members]]
name = "strongAttack"
type = "u16"
key = false

[[members]]
name = "healing"
type = "u16"
key = false
