// Generated by dojo-bindgen on Sat, 22 Jun 2024 20:40:02 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;


// Model definition for `dojo_starter::models::block::Block` model
public class Block : ModelInstance {
    [ModelField("gameId")]
    public uint gameId;

    [ModelField("x")]
    public ushort x;

    [ModelField("y")]
    public ushort y;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        