// Generated by dojo-bindgen on Sat, 22 Jun 2024 20:40:02 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;


// Model definition for `dojo_starter::models::player::Player` model
public class Player : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("score")]
    public ulong score;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        