// Generated by dojo-bindgen on Sat, 22 Jun 2024 20:40:02 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;


// Model definition for `dojo_starter::models::skill::Skill` model
public class Skill : ModelInstance {
    [ModelField("entityId")]
    public FieldElement entityId;

    [ModelField("gameId")]
    public uint gameId;

    [ModelField("attack")]
    public ushort attack;

    [ModelField("strongAttack")]
    public ushort strongAttack;

    [ModelField("healing")]
    public ushort healing;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        